import pa2

print(pa2.getHammingDistance("AACCTT","GGCCTT"))
print(pa2.getHammingDistance("TCGGA","AAAAG"))
print(pa2.getHammingDistance("A","AG"))
print(pa2.getHammingDistance("","AG"))
print(pa2.countSubstrPattern("AATATATAGG","GG"))
print(pa2.countSubstrPattern("AATATATAGG","ATA"))
print(pa2.countSubstrPattern("AATATATAGG","ACTGACTGACTG"))
print(pa2.isValidString("AAGGCTATGC","ACGT"))
print(pa2.isValidString("AAGGCTATGa","ACGT"))
print(pa2.isValidString("ACGT","ACGT"))
print(pa2.isValidString("ACGT101_","ACGT"))
print(pa2.isValidString("091212345","0123456789"))
print(pa2.getSkew("GGCCAC", 1))
print(pa2.getSkew("GGCCAC", 2))
print(pa2.getSkew("GGCCAC", 3))
print(pa2.getSkew("GGCCAC", 4))
print(pa2.getSkew("GGCCAC", 5))
print(pa2.getMaxSkewN("GGCCAC", 1))
print(pa2.getMaxSkewN("GGCCAC", 2))
print(pa2.getMaxSkewN("GGCCAC", 3))
print(pa2.getMaxSkewN("GGCCAC", 4))
print(pa2.getMaxSkewN("GGCCAC", 5))
print(pa2.getMaxSkewN("GGCCAC", 6))
print(pa2.getMinSkewN("GGCCAC", 1))
print(pa2.getMinSkewN("GGCCAC", 2))
print(pa2.getMinSkewN("GGCCAC", 3))
print(pa2.getMinSkewN("GGCCAC", 4))
print(pa2.getMinSkewN("GGCCAC", 5))
print(pa2.getMinSkewN("GGCCAC", 6))